"""init

Revision ID: 056cb42fc77a
Revises: 
Create Date: 2026-02-26 18:26:44.934800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '056cb42fc77a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('instance_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'email', name='uix_clients_name_email')
    )
    op.create_table('operators',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('instance_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('online', 'offline', 'busy')", name='ck_operators_check_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'email', name='uix_operators_name_email')
    )
    op.create_table('tickets',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('operator_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('status_last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('priority', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('instance_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('low', 'normal', 'high')", name='ck_tickets_check_priority'),
    sa.CheckConstraint("status IN ('new', 'in_progress', 'waiting', 'resolved', 'closed')", name='ck_tickets_check_status'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_client', 'tickets', ['client_id'], unique=False)
    op.create_index('idx_operator', 'tickets', ['operator_id'], unique=False)
    op.create_index('idx_operator_status', 'tickets', ['operator_id', 'status'], unique=False)
    op.create_index('idx_status', 'tickets', ['status'], unique=False)
    op.create_index('idx_status_last_updated', 'tickets', ['status_last_updated'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('ticket_id', sa.BigInteger(), nullable=False),
    sa.Column('author_type', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('instance_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("author_type IN ('client', 'operator')", name='ck_messages_check_author_type'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_index('idx_status_last_updated', table_name='tickets')
    op.drop_index('idx_status', table_name='tickets')
    op.drop_index('idx_operator_status', table_name='tickets')
    op.drop_index('idx_operator', table_name='tickets')
    op.drop_index('idx_client', table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('operators')
    op.drop_table('clients')
    # ### end Alembic commands ###
